spring.datasource.url=jdbc:mysql://localhost:3307/vacancy_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.open-in-view=false

scraper.schedule.fixed-delay-ms=3600000
scraper.max-vacancies=200
